services:
  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - ./cache/mongodb:/data/db
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ./cache/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=betterdo
