import { defineRelationsPart, type TablesRelationalConfig } from "drizzle-orm";
import * as authSchema from "./auth.js";
import * as taskSchema from "./task.js";
import * as listSchema from "./list.js";
import * as notificationSchema from "./notification.js";

const schema = {
  ...authSchema,
  ...taskSchema,
  ...listSchema,
  ...notificationSchema
};

// Auth relations (user <-> session/account/passkey) are generated by the
// better-auth CLI into `auth.ts` as `authRelations` via `defineRelationsPart`.
// We consume that part directly instead of re-declaring it here, so it never
// drifts from the generated schema.
const { authRelations } = authSchema;

// App-owned relations. Declared as a `defineRelationsPart` fragment so every
// relations definition in the codebase uses the same API. Each `r.many.*`
// without `from`/`to` is resolved against its reverse `r.one.*` within this
// same part, so both sides must live here together.
const appRelations = defineRelationsPart(schema, r => ({
  user: {
    pushSubscriptions: r.many.pushSubscriptions(),
    scheduledNotifications: r.many.scheduledNotifications(),
    lists: r.many.lists()
  },
  pushSubscriptions: {
    user: r.one.user({
      from: r.pushSubscriptions.userId,
      to: r.user.id
    })
  },
  scheduledNotifications: {
    user: r.one.user({
      from: r.scheduledNotifications.userId,
      to: r.user.id
    })
  },
  lists: {
    createdBy: r.one.user({
      from: r.lists.createdById,
      to: r.user.id
    }),
    members: r.many.listMembers()
  },
  listMembers: {
    list: r.one.lists({
      from: r.listMembers.listId,
      to: r.lists.id,
      optional: false
    }),
    user: r.one.user({
      from: r.listMembers.userId,
      to: r.user.id,
      optional: false
    })
  },
  tasks: {
    list: r.one.lists({
      from: r.tasks.listId,
      to: r.lists.id
    }),
    createdBy: r.one.user({
      from: r.tasks.createdById,
      to: r.user.id
    })
  }
}));

// Type-level counterpart of the runtime merge below: for every table key across
// both parts, merge their `relations` sub-objects (mirroring the runtime deep
// merge) so `db.query.*.with` sees auth-side AND app-side relations.
type MergeRelationParts<A, B> = {
  [K in keyof A | keyof B]: K extends keyof A
    ? K extends keyof B
      ? Omit<A[K], "relations"> & {
          relations: (A[K] extends { relations: infer RA } ? RA : object) &
            (B[K] extends { relations: infer RB } ? RB : object);
        }
      : A[K]
    : K extends keyof B
      ? B[K]
      : never;
};

// Combine two relation parts. Unlike the docs' `{ ...main, ...part }` spread
// (which replaces whole per-table entries), this merges the `relations` objects
// of tables that appear in both parts — required because `user` is declared in
// both `authRelations` (generated) and `appRelations`. The generic return type
// mirrors the runtime deep merge, so no cast is needed at the call site. See
// relations.test.ts.
export function mergeRelationParts<A extends TablesRelationalConfig, B extends TablesRelationalConfig>(
  a: A,
  b: B
): MergeRelationParts<A, B> {
  const merged: TablesRelationalConfig = {};
  for (const part of [a, b]) {
    for (const [tableName, tableConfig] of Object.entries(part)) {
      const existing = merged[tableName];
      if (existing) {
        existing.relations = { ...existing.relations, ...tableConfig.relations };
      } else {
        merged[tableName] = { ...tableConfig, relations: { ...tableConfig.relations } };
      }
    }
  }
  return merged as MergeRelationParts<A, B>;
}

export const relations = mergeRelationParts(authRelations, appRelations);
